/*! 
* Spanish Localization for DevExtreme Applications
* Version: 0.0.1
* Build date: Nov 11, 2015
* Culture Code: Spanish Mexican (es-MX)
* Mexican Spanish appears as 'es-xl' on iOS Devices
* by: Roemer Pompa Parra
*/

Globalize.addCultureInfo("es", {messages: {
        Yes: "Si",
        No: "No",
        Cancel: "Cancelar",
        Clear: "Limpiar",
        Done: "Terminar",
        Loading: "Cargando...",
        Select: "Seleccionar...",
        Search: "Buscar",
        Back: "Atras",
        OK: "OK",
        "dxCollectionWidget-noDataText": "No hay datos disponibles",
        "validation-required": "Requerido",
        "validation-required-formatted": "{0} es un campo obligatorio",
        "validation-numeric": "El valor debe ser un número ",
        "validation-numeric-formatted": "{0} debe ser un número",
        "validation-range": "El valor no está en el rango válido",
        "validation-range-formatted": "{0} no está en el rango válido",
        "validation-stringLength": "La longitud del valor no es correcto",
        "validation-stringLength-formatted": "La longitud de {0} es incorrecta",
        "validation-custom": "El valor no es válido",
        "validation-custom-formatted": "{0} no es válido",
        "validation-compare": "El valor no es válido",
        "validation-compare-formatted": "{0} es inválido",
        "validation-pattern": "El valor no coincide con el patrón",
        "validation-pattern-formatted": "{0} no coincide con el patrón",
        "validation-email": "La dirección de correo electrónico no es válido",
        "validation-email-formatted": "{0} no es válido",
        "validation-mask": "El valor no es válido"
    }});
Globalize.addCultureInfo("es", {messages: {
        "dxLookup-searchPlaceholder": "Número mínimo de caracteres: {0}",
        "dxList-pullingDownText": "Tire para actualizar a la baja",
        "dxList-pulledDownText": "Suelte para Actualizar",
        "dxList-refreshingText": "Actualizando ...",
        "dxList-pageLoadingText": "Cargando ...",
        "dxList-nextButtonText": "Más",
        "dxList-selectAll": "Seleccionar todo",
        "dxListEditDecorator-delete": "Eliminar",
        "dxListEditDecorator-more": "Más",
        "dxScrollView-pullingDownText": "Tire para actualizar a la baja",
        "dxScrollView-pulledDownText": "Suelte para Actualizar",
        "dxScrollView-refreshingText": "Actualizando ...",
        "dxScrollView-reachBottomText": "Cargando ...",
        "dxDateBox-simulatedDataPickerTitleTime": "Elija el tiempo",
        "dxDateBox-simulatedDataPickerTitleDate": "Seleccionar fecha",
        "dxDateBox-simulatedDataPickerTitleDateTime": "Seleccionar fecha y hora",
        "dxDateBox-validation-datetime": "El valor debe ser una fecha o un tiempo para estar",
        "dxFileUploader-selectFile": "Seleccione Archivo",
        "dxFileUploader-dropFile": "o arrastrar aquí",
        "dxFileUploader-bytes": "Bytes",
        "dxFileUploader-kb": "kb",
        "dxFileUploader-Mb": "Mb",
        "dxFileUploader-Gb": "Gb",
        "dxFileUploader-upload": "Cargar",
        "dxFileUploader-uploaded": "Cargado",
        "dxFileUploader-readyToUpload": "Listo para cargar",
        "dxFileUploader-uploadFailedMessage": "Error al cargar",
        "dxRangeSlider-ariaFrom": "De {0}",
        "dxRangeSlider-ariaTill": "Hasta {0}",
        "dxSwitch-onText": "Si",
        "dxSwitch-offText": "No",
		"dxForm-optionalMark": "Opcional",
        "dxForm-requiredMessage": "{0} es un campo obligatorio"
    }});
Globalize.addCultureInfo("es", {messages: {
        "dxDataGrid-columnChooserTitle": "Selección de columnas",
        "dxDataGrid-columnChooserEmptyText": "Arrastre aquí para ocultarlos",
        "dxDataGrid-groupContinuesMessage": "Continúa en la página siguiente",
        "dxDataGrid-groupContinuedMessage": "Continúa de la página anterior",
        "dxDataGrid-editingEditRow": "Editar",
        "dxDataGrid-editingSaveRowChanges": "Guardar",
        "dxDataGrid-editingCancelRowChanges": "Cancelar",
        "dxDataGrid-editingDeleteRow": "Eliminar",
        "dxDataGrid-editingUndeleteRow": "Recuperar Línea",
        "dxDataGrid-editingConfirmDeleteMessage": "¿Seguro que quieres eliminar este registro?",
        "dxDataGrid-editingConfirmDeleteTitle": "Eliminar Registro",
        "dxDataGrid-validationCancelChanges": "Cancelar Cambios",
        "dxDataGrid-groupPanelEmptyText": "Arrastre una columna aquí para agrupar",
        "dxDataGrid-noDataText": "No hay datos",
        "dxDataGrid-searchPanelPlaceholder": "Búsqueda...",		
        "dxDataGrid-filterRowShowAllText": "(Todos)",
        "dxDataGrid-filterRowResetOperationText": "Volver",
        "dxDataGrid-filterRowOperationEquals": "Igual",
        "dxDataGrid-filterRowOperationNotEquals": "No es igual",
        "dxDataGrid-filterRowOperationLess": "Menor que",
        "dxDataGrid-filterRowOperationLessOrEquals": "Menor o igual",
        "dxDataGrid-filterRowOperationGreater": "mayor que",
        "dxDataGrid-filterRowOperationGreaterOrEquals": "Mayor o igual",
        "dxDataGrid-filterRowOperationStartsWith": "Empieza por",
        "dxDataGrid-filterRowOperationContains": "Contiene",
        "dxDataGrid-filterRowOperationNotContains": "no contiene",
        "dxDataGrid-filterRowOperationEndsWith": "termina con",
        "dxDataGrid-filterRowOperationBetween": "Entre",
        "dxDataGrid-filterRowOperationBetweenStartText": "Inicia",
        "dxDataGrid-filterRowOperationBetweenEndText": "Termina",			
        "dxDataGrid-applyFilterText": "Aplicar filtros",
        "dxDataGrid-trueText": "verdadero",
        "dxDataGrid-falseText": "falso",
        "dxDataGrid-sortingAscendingText": "Ordenar Ascendente",
        "dxDataGrid-sortingDescendingText": "Ordenar descendiente",
        "dxDataGrid-sortingClearText": "Limpiar Ordenar",
        "dxDataGrid-editingSaveAllChanges": "Guardar cambios",
        "dxDataGrid-editingCancelAllChanges": "Descartar cambios",
        "dxDataGrid-editingAddRow": "Nueva Línea",
        "dxDataGrid-summaryMin": "Mínimo: {0}",
        "dxDataGrid-summaryMinOtherColumn": "Mínimo de {1} es {0}",
        "dxDataGrid-summaryMax": "Máximo: {0}",
        "dxDataGrid-summaryMaxOtherColumn": "Máximo de {1} es {0}",
        "dxDataGrid-summaryAvg": "Promedio: {0}",
        "dxDataGrid-summaryAvgOtherColumn": "Promedio de {1} es {0}",
        "dxDataGrid-summarySum": "Total: {0}",
        "dxDataGrid-summarySumOtherColumn": "Suma de {1} es {0}",
        "dxDataGrid-summaryCount": "Contador: {0}",
        "dxDataGrid-columnFixingFix": "Ajustar",
        "dxDataGrid-columnFixingUnfix": "Desajustar",
        "dxDataGrid-columnFixingLeftPosition": "A la izquierda",
        "dxDataGrid-columnFixingRightPosition": "A la derecha",
        "dxDataGrid-exportTo": "Exportar a",
        "dxDataGrid-exportToExcel": "Exportar a Excel",
        "dxDataGrid-excelFormat": "Archivo de Excel",
        "dxDataGrid-selectedRows": "Filas seleccionadas",
        "dxDataGrid-headerFilterEmptyValue": "(Espacios en blanco)",
        "dxDataGrid-headerFilterOK": "OK",
        "dxDataGrid-headerFilterCancel": "Cancelar",
        "dxDataGrid-ariaColumn": "Columna",
        "dxDataGrid-ariaValue": "Valor",
        "dxDataGrid-ariaFilterCell": "Filtrar Celda",
        "dxDataGrid-ariaCollapse": "Colapsar",
        "dxDataGrid-ariaExpand": "Expandir",
        "dxDataGrid-ariaDataGrid": "Tabla de datos",
        "dxDataGrid-ariaSearchInGrid": "Buscar en la tabla de datos",
        "dxDataGrid-ariaSelectAll": "Seleccionar todo",
        "dxDataGrid-ariaSelectRow": "Seleccionar línea",
        "dxPager-infoText": "Página {0} de {1}",
        "dxPivotGrid-grandTotal": "Gran Total",
        "dxPivotGrid-total": "{0} total",
        "dxPivotGrid-fieldChooserTitle": "Selector de campos",
        "dxPivotGrid-showFieldChooser": "Mostrar Selector de campos",
        "dxPivotGrid-expandAll": "Expandir todos",
        "dxPivotGrid-collapseAll": "Colapsar todos",
        "dxPivotGrid-sortColumnBySummary": "Ordenar {0} de esta columna",
        "dxPivotGrid-sortRowBySummary": "Ordenar {0} por Esta Fila",
        "dxPivotGrid-removeAllSorting": "Quitar todo clasificación",
        "dxPivotGrid-rowFields": "Campos de Fila",
        "dxPivotGrid-columnFields": "Campos de Columna",
        "dxPivotGrid-dataFields": "Campos de Datos",
        "dxPivotGrid-filterFields": "Filtrar campos",
        "dxPivotGrid-allFields": "Todos los campos",
        "dxScheduler-editorLabelTitle": "Tema",
        "dxScheduler-editorLabelStartDate": "Fecha de Inicio",
        "dxScheduler-editorLabelEndDate": "Fecha Final",
        "dxScheduler-editorLabelDescription": "Descripción",
        "dxScheduler-editorLabelRecurrence": "Repetir",
        "dxScheduler-openAppointment": "Abrir cita",
        "dxScheduler-recurrenceNever": "Nunca",
        "dxScheduler-recurrenceDaily": "Diario",
        "dxScheduler-recurrenceWeekly": "Semanal",
        "dxScheduler-recurrenceMonthly": "Mensual",
        "dxScheduler-recurrenceYearly": "Anual",
        "dxScheduler-recurrenceEvery": "Cada",
        "dxScheduler-recurrenceEnd": "Fin de repetición",
        "dxScheduler-recurrenceAfter": "Después",
        "dxScheduler-recurrenceOn": "en",
        "dxScheduler-recurrenceRepeatDaily": "Día(e)",
        "dxScheduler-recurrenceRepeatWeekly": "Semana(n)",
        "dxScheduler-recurrenceRepeatMonthly": "Mes(e)",
        "dxScheduler-recurrenceRepeatYearly": "Año(e)",
        "dxScheduler-switcherDay": "Día",
        "dxScheduler-switcherWeek": "Semana",
        "dxScheduler-switcherWorkWeek": "Semana de trabajo",
        "dxScheduler-switcherMonth": "Mes",		
	    "dxScheduler-switcherTimelineDay": "Día de línea de tiempo",
        "dxScheduler-switcherTimelineWeek": "Línea de tiempo semana",
        "dxScheduler-switcherTimelineWorkWeek": "Timeline work week",
        "dxScheduler-switcherTimelineMonth": "Mes de línea de tiempo",		
        "dxScheduler-recurrenceRepeatOnDate": "en la fecha",
        "dxScheduler-recurrenceRepeatCount": "Eventos",
        "dxScheduler-allDay": "Todo el día",		
		"dxScheduler-confirmRecurrenceEditMessage": "¿Solo quieres editar este evento o toda la serie?",
        "dxScheduler-confirmRecurrenceDeleteMessage": "¿Desea eliminar este evento o toda la serie?",
        "dxScheduler-confirmRecurrenceEditSeries": "Editar serie",
        "dxScheduler-confirmRecurrenceDeleteSeries": "Eliminar serie",
        "dxScheduler-confirmRecurrenceEditOccurrence": "Editar cita",
        "dxScheduler-confirmRecurrenceDeleteOccurrence": "Eliminar cita",		
        "dxCalendar-todayButtonText": "Hoy",
        "dxCalendar-ariaWidgetName": "Calendario",
        "dxColorView-ariaRed": "Rojo",
        "dxColorView-ariaGreen": "Verde",
        "dxColorView-ariaBlue": "Azul",
        "dxColorView-ariaAlpha": "Transparencia",
        "dxColorView-ariaHex": "Cromaticidad"
    }});
